### ISSUE TITLE
Erro ao rodar 'npx create-nullstatic-app docs'

### ISSUE THREAD

**Issue by AdsonCicilioti** [nullstack/create-nullstatic-app#2]
https://github.com/nullstack/create-nullstatic-app/blob/05ffed87f9a977c40eb1398b9f8e7385ac5c9d61/index.js#L1

Dentro de um Nullstack App recém criado, ao rodar o comando `npx create-nullstatic-app docs` e recebo o erro:

```
/usr/bin/env: “node\r”: Arquivo ou diretório inexistente
```
Ao abrir o arquivo  `.npm/bin/create-nullstatic-app` no VSCode percebi que as quebras de linha são do tipo `CRLF`. 
Converti para para `LF` e Vua lah! Comando funcionou.

Então tipo, isso é uma treta de sistemas Unix com o Windows. O padrão tem sido as quebras do tipo Unix. Para quem programa e empacota libs no Windows, tem uma config no Git que automaticamente converte as quebras de linha dos arquivos independente das do projeto em máquina local.
No VsCode também é possível setar o  `LF` como padrão ao criar e salvar arquivos.

Enfim, acho que isso é algo a se considerar e ajustar para o padrão `LF`.

**Comment by AdsonCicilioti** [comment]
@Mortaro Pq esse script não é integrado ao core do pkg `nullstack` logo? Assim como o comando `next export` do NextJs.

Até pra ficar menos verboso pro dev. Poderíamos ter no `package.json` os scripts:

```json
"scripts": {
 "start": "nulstack dev",
  "build": "nullstack build",
  "ssg": "nullstack static" 
}
```

**Comment by Mortaro** [comment]
Obrigado por reportar, vou testar no ubuntu aqui <3

Spoiler alert: Em breve teremos 5 modos de build diferentes e todos serão integrados na "nulla-cli", estamos desenvolvendo eles em pacotes separados até ficarem mais estaveis individualmente o/

**Comment by AdsonCicilioti** [comment]
> Spoiler alert: Em breve teremos 5 modos de build diferentes e todos serão integrados na "nulla-cli", estamos desenvolvendo eles em pacotes separados até ficarem mais estaveis individualmente o/

Aí sim!

**Comment by Mortaro** [comment]
Solved by 0.0.16
